apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-sptrans-status-cartao-deploy
  namespace: consulta-sptrans
  labels:
    app: service-sptrans-status-cartao-deploy
spec:
  replicas: #{REPLICAS_SERVICES}
  selector:
    matchLabels:
      app: service-sptrans-status-cartao-deploy
  template:
    metadata:
      labels:
        app: service-sptrans-status-cartao-deploy
    spec:
      hostname: transporte-roteirizacao
      containers:
        - name: service-sptrans-status-cartao-sync
          image: #{DOCKER_REGISTRY}/consulta/svc-sptrans-status-cartao:#{RELEASE.ARTIFACTS._Transporte-svc-sptrans.BUILDID}
          env:
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: consulta-sptrans-secrets
                  key: Database__Password
            - name: Queue__Password
              valueFrom:
                secretKeyRef:
                  name: consulta-sptrans-secrets
                  key: Queue__Password
          envFrom:
            - configMapRef:
                name: consulta-sptrans-status-cartao-configmap
          resources:
            limits:
              memory: '256Mi'
              cpu: '1'
            requests:
              memory: '100Mi'
              cpu: '1m'
